language: go

go:
  # - 1.7.x
  # - 1.8.x
  # - 1.9.x
  - 1.10.x
  # - master

script:
  - go version
  - make setup
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
